server:
  port: 8081
  servlet:
    context-path: /api
collection:
  url: http://localhost:8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.131:3306/tanmu_video?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  redis:
    port: 6379
    host: 192.168.10.131
    database: 0
    prefix: 'tanmu::'
    expired-seconds: 72000


logging:
  level:
    root: info
    com.video.tanmu.dao: debug
  file:
    name: log/log.log
